name: example
description: A sample command-line application.
publish_to: none
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  t: any
  socks5_proxy: any
  tg:
    path: ../

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
